name: CI

on:
  push:
    tags: [ "**" ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Split tag name
        env:
          TAG: ${{ github.ref_name }}
        id: split
        run: |
          TAG_NAME="${{ github.ref_name }}"
          echo "PACKAGE_NAME=${TAG_NAME%%@*}" >> $GITHUB_OUTPUT
          echo "PACKAGE_VERSION=${TAG_NAME##*@}" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Download pkl
        shell: bash
        run: |
          wget -q -O pkl https://github.com/apple/pkl/releases/download/0.25.1/pkl-linux-amd64
          chmod a+x pkl
          ./pkl --version
          export PATH="$PATH:$(pwd)"
          cd ${{ steps.split.outputs.PACKAGE_NAME }}
          pkl project package --output-path=../.out
          mkdir ../.zips
          mv ../.out/*.zip* ../.zips/
      - name: Publish package file
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: static
          FOLDER: .out
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ".zips/*"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
