name: CI

on:
  push:
    tags: [ "**" ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Download pkl
        run: |
          wget -O pkl https://github.com/apple/pkl/releases/download/0.25.1/pkl-linux-amd64
          chmod a+x pkl
          ./pkl --version
          export PATH="$PATH:$(pwd)"
          for d in */ ; do
            pushd "$d"
            pkl project package --output-path=../.out
            popd
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkl-packages
          path: |
            .out
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: ${{ github.ref_name }}
